# Python for Data Analysis using Pandas (part 1 of 2)

> The latest version of this notebook is always found at [github.com/tommyod/awesome-pandas](https://github.com/tommyod/awesome-pandas).   
  Improvements, corrections or suggestions? **Please submit a [Pull Request](https://github.com/tommyod/awesome-pandas/pulls).**
  
  ![](pandas_vs_excel_vs_sas.png)

# Table of contents

- **(1) Setup**
  - (1.1) Installing Python and packages
  - (1.2) Importing packages
- **(2) Importing data**
  - (2.1) Importing .csv files
  - (2.2) Other ways of creating DataFrames
  - (2.3) Changing names and data types
- **(3) Summarizing data**
  - (3.1) Peeking at the data
  - (3.2) Null values and summary statistics
  - (3.3) Unique values, value counts and sorting
  - (3.4) Basic visualizations
- **(4) Selecting and computing new columns**
  - (4.1) Accessing rows, columns and data
  - (4.2) Selecting subsets of columns
  - (4.3) Selecting subsets of rows
  - (4.4) Selecting subsets of rows *and* columns
  - (4.5) Creating new columns
  - (4.6) Applying functions
  
  
**In the next video:** filtering and sorting, split-apply-combine, plotting, time series, machine learning, ...

---------------------------------

# (1) Setup

## (1.1) Installing Python and packages

### Python and Anaconda

If you haven't done it yet, you need to install Python.
I recommend the [Anaconda Distribution](https://www.anaconda.com/download/), and you should install version `3.X`.
- If you're on Windows, you will get a program called *Anaconda Prompt*. Open in and run `conda --version` to verify that everything works.
- If you're on Linux, open a terminal and run `conda --version`.

Type `conda list` to see every installed package, and `conda update --all` to update every package. Type `python` to open an interactive Python terminal, and `exit()` to leave.

### NumPy, matplotlib and Pandas

![](https://indranilsinharoy.files.wordpress.com/2013/01/scientificpythonecosystemsi.png?w=584&h=442)

*Image source: https://indranilsinharoy.com/2013/01/06/python-for-scientific-computing-a-collection-of-resources/*

To install indiviual packages, run `conda install <package>`.   
The Anaconda distribution comes with 3 packages which this tutorial requires, namely [pandas](https://pandas.pydata.org/), [NumPy](http://www.numpy.org/) and [matplotlib](https://matplotlib.org/).
We'll also briefly use [sklearn](https://scikit-learn.org/stable/).

- **NumPy** implements $n$-dimensional arrays in Python for efficient numerical computations. See the [arXiv](https://arxiv.org/pdf/1102.1523.pdf) paper for a nice introduction. To learn basic NumPy, consider doing these [100 NumPy exercises](https://github.com/rougier/numpy-100). For an in-depth look at NumPy and vectorization to speed up scientific computing, see [From Python to Numpy
](https://www.labri.fr/perso/nrougier/from-python-to-numpy/).
- **Matplotlib** is the most popular library for plotting in Python. See the beautiful [gallery](https://matplotlib.org/gallery.html) to get an overview of the capabilities of matplotlib. Read the [Matplotlib tutorial](http://www.labri.fr/perso/nrougier/teaching/matplotlib/matplotlib.html) by Nicolas P. Rougier for an introduction.
- **Pandas** is a library for data analysis based on two objects, the [Series](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html) and the [DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html).

### Jupyter

A [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/) is an environment for running Python code interactively, displaying graphs and working with data. Think of it as a tool with capabilities somewhere between a simple terminal and a full fledged IDE. Move to a directory using the `cd` command in the terminal, then run `jupyter notebook` to start up a notebook. A video introduction to JupyterLab is [JupyterLab: Building Blocks for Interactive Computing](https://www.youtube.com/watch?v=Ejh0ftSjk6g). See also this list of [28 Jupyter Notebook tips](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/).

## (1.2) Importing packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
# import KDEpy
import sklearn
%matplotlib inline

### Package versions

To make this Jupyter Notebook more easily reproducible, we list versions of the libraries we will be using.

In [2]:
import datetime

print('Today is', datetime.datetime.utcnow())
print('-'*2**6)

for lib in [pd, np, matplotlib,sklearn]:
    print(f'{lib.__name__.ljust(12)} version {lib.__version__}')

Today is 2025-04-13 15:38:12.835789
----------------------------------------------------------------
pandas       version 2.2.3
numpy        version 2.0.1
matplotlib   version 3.10.0
sklearn      version 1.6.1

C:\Users\5\AppData\Local\Temp\ipykernel_24276\1132212279.py:3: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  print('Today is', datetime.datetime.utcnow())

### Using Jupyter Notebooks

- Useful shortcuts: `SHIFT + TAB`, `SHIFT + ENTER`, `ESC`, `ENTER`, `E`, `A`, `D,D`, `I, I`. Type `H` to see all shortcuts.
- Executing terminal commands from within the notebook using `!`.
- Using markdown and $\LaTeX{}$.
- Timing cells using `%%timeit` and other built-in magic commands.
- Pitfalls when using notebooks: state, order of execution, tidyness.

Example of $\LaTeX{}$ usage in notebooks:

$$0 \leq
  \left[\operatorname{tr}(\mathbf{A} \mathbf{B})\right]^2 \leq
  \operatorname{tr}\left(\mathbf{A}^2\right) \operatorname{tr}\left(\mathbf{B}^2\right) \leq
  \left[\operatorname{tr}(\mathbf{A})\right]^2 \left[\operatorname{tr}(\mathbf{B})\right]^2$$
$$\varphi_X(t) = \operatorname{E}\left[\exp \left ({i\int_\mathbf{R} t(s)X(s)ds} \right ) \right]$$

# (2) Importing data

Starting a cell with a `!` let's us use terminal commands. The UNIX `head` command shows the first rows of the file.

## (2.1) Importing `.csv` files

In [3]:
!tree . -L 2

Too many parameters - -L

In [4]:
!head data/movie_metadata.csv -n 2

'head' is not recognized as an internal or external command,
operable program or batch file.

> **Interested in learning UNIX commands?** The book [The Linux Command Line](https://www.amazon.com/Linux-Command-Line-Complete-Introduction-ebook/dp/B006X2QEQS) gives a detailed introduction, and [Data Science at the Command Line](https://www.amazon.com/Data-Science-Command-Line-Time-Tested/dp/1491947853) shows how basic data manipulation may be done using the command line only.

The file has many columns, so we'll only load a couple into a pandas DataFrame.
To familiarize ourselves with with [magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html), we'll use `%%time` to time the execution of the cell below.

In [3]:
%%time

cols_to_use = ['movie_title', 'director_name', 'country', 'content_rating', 'imdb_score', 'gross']

df = pd.read_csv(r'data/movie_metadata.csv', sep=',', usecols=cols_to_use)

print(f'Loaded data of size {df.shape} into memory.')

Loaded data of size (5043, 6) into memory.
CPU times: total: 15.6 ms
Wall time: 18 ms

In [6]:
df.head(2)  # Show the top 2 rows

,director_name,gross,movie_title,country,content_rating,imdb_score
0,James Cameron,760505847.0,Avatar,USA,PG-13,7.9
1,Gore Verbinski,309404152.0,Pirates of the Caribbean: At World's End,USA,PG-13,7.1

The `df.shape` attribute gives the rows and columns of the DataFrame.

In [7]:
df.shape  # Alternatively, use len(df) for row count

(5043, 6)

## (2.2) Other ways of creating DataFrames

**The DataFrame**

> Two-dimensional size-mutable, potentially heterogeneous tabular data
structure with **labeled axes** (rows and columns). Arithmetic operations
align on both row and column labels. Can be thought of as a **dict-like
container for Series objects**. The primary pandas data structure.

**Creating a DataFrame from scratch**

In [8]:
pd.DataFrame({'name':['Max', 'Mark', 'Mia'], 'age':[31, 25, 38]})

   name  age
0   Max   31
1  Mark   25
2   Mia   38

**Reading a HTML table from the web**

In [9]:
# Read HTML tables into a list of DataFrame objects.
url = r'https://en.wikipedia.org/wiki/List_of_Germans_by_net_worth'
tables = pd.read_html(url, header=0)

df_net_worth = tables[0]

# Asserts can be useful for sanity checks
assert len(df_net_worth) > 0 
assert df_net_worth.Name.is_unique


df_net_worth.head()

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

**Reading from databases is also possible.**

Reading from Microsoft SQL using `pyodbc` and `pd.read_sql(sql_code, connection)`.

---------

> **Gotcha.** Methods on DataFrames **return a new instance** by default. In other words, they behave like methods on *immutable* Python object, and not like methods on *mutable* objects.

In [ ]:
# Lists are MUTABLE
scores = [6, 2, 4, 9, 1]
scores.sort()  # Changes the object in-place, returns None
print(scores)

# Strings are IMMUTABLE
my_name = 'tommy'
my_name = my_name.capitalize()  # A new instance is returned
print(my_name)

[1, 2, 4, 6, 9]
Tommy

## (2.3) Changing names and data types

In [ ]:
# Alter axes labels
df_net_worth = (df_net_worth
                .rename(columns={'Net worth (USD)': 'net_worth',
                                'World ranking': 'world_ranking',
                                'Sources of wealth': 'wealth_source'}))

df.rename(columns=str.capitalize).head(2)

The data type of each column may be listed using `df.dtypes`. Automatic conversion is possible via `pd.to_numeric` and `pd.to_datetime`.

In [ ]:
df.dtypes

director_name      object
gross             float64
movie_title        object
country            object
content_rating     object
imdb_score        float64
dtype: object

In [ ]:
# df_net_worth['net_worth_num'] = (df_net_worth['net_worth']
#                              .str.replace(' billion', '')
#                              .apply(float))

# df_net_worth.head(2)

NameError: name 'df_net_worth' is not defined

### Getting help

There are many ways to help help on objects and methods.

- Use `SHIFT TAB` in a notebook.
- Use question marks in the notebook, e.g. `?df.sum`.
- Use the built-in Python function `help`, e.g. `help(df.sum)`.

In [ ]:
# df.sum?

# (3) Summarizing data

This section shows some important methods related to summarizing data.

## (3.1) Peeking at the data

Three methods that are useful when peeking at the data are `df.head`, `df.tail` and `df.sample`.
Head and tail are $\mathcal{O}(1)$ operations, while sample is $\mathcal{O}(n)$, where $n$ is the number of rows.
For small datasets, this makes no difference in practice. We'll use `df.sample` here.

In [ ]:
# Return the first `n` rows.
df.head(n=2)  # df.tail(n=2) returns the last rows

,director_name,gross,movie_title,country,content_rating,imdb_score
0,James Cameron,760505847.0,Avatar,USA,PG-13,7.9
1,Gore Verbinski,309404152.0,Pirates of the Caribbean: At World's End,USA,PG-13,7.1

In [ ]:
df.sample(n=2, replace=False, weights=None, random_state=None)

,director_name,gross,movie_title,country,content_rating,imdb_score
4262,Jack Conway,NaN,Boom Town,USA,Passed,7.1
830,Brett Ratner,28328132.0,After the Sunset,USA,PG-13,6.3

## (3.2) Null values and summary statistics

We should make sure the data types are correct. To do so, we can use `df.dtypes`, or `df.info()` for some more information.

In [ ]:
# Print a concise summary of a DataFrame
# df.info(verbose=True, memory_usage=True, null_counts=True)

TypeError: DataFrame.info() got an unexpected keyword argument 'null_counts'

We have some null values. Let's count them by chaining `df.isnull()` and `df.sum()`.

In [ ]:
# Detect missing values -> sum over rows
null_values = df.isnull().sum(axis=0)
null_values #  / len(df)

director_name     104
gross             884
movie_title         0
country             5
content_rating    303
imdb_score          0
dtype: int64

The result of the above is not a DataFrame object, but a Series.

In [ ]:
nan_values = df.isna().sum(axis=0)
nan_values

director_name     104
gross             884
movie_title         0
country             5
content_rating    303
imdb_score          0
dtype: int64

In [ ]:
type(null_values)

pandas.core.series.Series

![alt text](https://www.mathsisfun.com/algebra/images/scalar-vector-matrix.svg)
*Image source:* https://www.mathsisfun.com/algebra/scalar-vector-matrix.html

We can make the output prettier by converting the `null_values` Series to a DataFrame using the `to_frame()` method, then transposing using `.T`, and finally renaming the first index.

In [ ]:
null_values.to_frame()

                  0
director_name   104
gross           884
movie_title       0
country           5
content_rating  303
imdb_score        0

In [ ]:
null_values.to_frame().T

   director_name  gross  movie_title  country  content_rating  imdb_score
0            104    884            0        5             303           0

In [ ]:
null_values.to_frame().T.rename(index={0: 'Missing values'})

,director_name,gross,movie_title,country,content_rating,imdb_score
Missing values,104,884,0,5,303,0

The above is called *method chaining*, and can be written like so:

In [ ]:
(df
    .isnull()    # Figure out whether every entry is null (missing), or not
    .sum(axis=0) # Sum over each column, axis=0 is the default
    .to_frame()  # The result is a Series, convert to DataFrame
    .T           # Transpose (switch rows and columns)
    .rename(index={0:'Missing values'}) # Rename the index and show it
)

,director_name,gross,movie_title,country,content_rating,imdb_score
Missing values,104,884,0,5,303,0

A tour of summarization would not be complete without `df.describe()`.  
Calling `df.count()`, `df.nunique()`, `df.mean()`, `df.std()`, `df.min()`, `df.quantile()`, `df.max()` is also possible.

> **Gotcha.** There are 200+ methods defined on a DataFrame. See the [API Reference](https://pandas.pydata.org/pandas-docs/stable/api.html) for an exhaustive list.

In [ ]:
# dir(pd.DataFrame)
df.describe(percentiles=[0.5], include='all').fillna('')

In [ ]:
df.shape

(5043, 6)

In [12]:
len(df.columns)

6

In [24]:
len(df)

5043

In [20]:
dfc = df

dfc.dropna(axis=0, how='any').shape

(4092, 6)

In [21]:
dfc = df
dfc.drop_duplicates(subset=None)

,director_name,gross,movie_title,country,content_rating,imdb_score
0,James Cameron,760505847.0,Avatar,USA,PG-13,7.9
1,Gore Verbinski,309404152.0,Pirates of the Caribbean: At World's End,USA,PG-13,7.1
2,Sam Mendes,200074175.0,Spectre,UK,PG-13,6.8
3,Christopher Nolan,448130642.0,The Dark Knight Rises,USA,PG-13,8.5
4,Doug Walker,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,7.1
...,...,...,...,...,...,...
5038,Scott Smith,NaN,Signed Sealed Delivered,Canada,NaN,7.7
5039,NaN,NaN,The Following,USA,TV-14,7.5
5040,Benjamin Roberds,NaN,A Plague So Pleasant,USA,NaN,6.3
5041,Daniel Hsia,10443.0,Shanghai Calling,USA,PG-13,6.3
5042,Jon Gunn,85222.0,My Date with Drew,USA,PG,6.6

In [35]:
dfc = df
ss = dfc.duplicated()
# type(dfc[dfc.duplicated()])
(dfc[dfc.duplicated()]).sort_values('movie_title')
# ss

,director_name,gross,movie_title,country,content_rating,imdb_score
4894,Richard Fleischer,NaN,"20,000 Leagues Under the Sea",USA,Approved,7.2
4950,David Hewlett,NaN,A Dog's Breakfast,Canada,NaN,7.0
4352,Wes Craven,26505000.0,A Nightmare on Elm Street,USA,X,7.5
4408,Yimou Zhang,190666.0,"A Woman, a Gun and a Noodle Shop",China,R,5.7
4842,Julie Taymor,24343673.0,Across the Universe,USA,PG-13,7.4
...,...,...,...,...,...,...
1220,Angelina Jolie Pitt,115603980.0,Unbroken,USA,PG-13,7.2
3981,Jaume Collet-Serra,61094903.0,Unknown,UK,PG-13,6.9
1305,Paul McGuigan,5773519.0,Victor Frankenstein,USA,PG-13,6.0
2099,Paul McGuigan,5773519.0,Victor Frankenstein,USA,PG-13,6.0
2169,Paul McGuigan,12831121.0,Wicker Park,USA,PG-13,7.0

In [ ]:
dfc = df
dfc.drop_duplicates(subset=None).shape  # Use df[df.duplicated()] to see rows

In [ ]:
dfc = df
dfc = dfc.dropna(axis=0, how='any').drop_duplicates(subset=None)

## (3.3) Unique values, value counts and sorting

In [ ]:
dfc.content_rating.unique()   # Not the same as: df.content_rating.is_unique

array(['PG-13', nan, 'PG', 'G', 'R', 'TV-14', 'TV-PG', 'TV-MA', 'TV-G',
       'Not Rated', 'Unrated', 'Approved', 'TV-Y', 'NC-17', 'X', 'TV-Y7',
       'GP', 'Passed', 'M'], dtype=object)

In [39]:
len(dfc.content_rating.unique())

19

In [5]:
df.index.is_unique

True

In [36]:
print(dfc.content_rating.drop_duplicates().tolist())

['PG-13', nan, 'PG', 'G', 'R', 'TV-14', 'TV-PG', 'TV-MA', 'TV-G', 'Not Rated', 'Unrated', 'Approved', 'TV-Y', 'NC-17', 'X', 'TV-Y7', 'GP', 'Passed', 'M']

In [37]:
dfc.content_rating.value_counts()

content_rating
R            2118
PG-13        1461
PG            701
Not Rated     116
G             112
Unrated        62
Approved       55
TV-14          30
TV-MA          20
TV-PG          13
X              13
TV-G           10
Passed          9
NC-17           7
GP              6
M               5
TV-Y            1
TV-Y7           1
Name: count, dtype: int64

In [40]:
dfc[['movie_title', 'gross']].nlargest(3, 'gross')

        movie_title        gross
0           Avatar   760505847.0
26         Titanic   658672302.0
29  Jurassic World   652177271.0

In [41]:
# Sort by country, then by IMDB_score. Put NA values last
dfc.sort_values(by=['country', 'imdb_score'], 
               ascending=[True, False], 
               na_position='last').head()

,director_name,gross,movie_title,country,content_rating,imdb_score
4735,Siddiq Barmak,1127331.0,Osama,Afghanistan,PG-13,7.4
4000,Juan José Campanella,20167424.0,The Secret in Their Eyes,Argentina,R,8.2
4415,Fabián Bielinsky,1221261.0,Nine Queens,Argentina,R,7.9
4666,Jorge Gaggero,NaN,Live-In Maid,Argentina,Unrated,7.2
4450,Lucrecia Martel,304124.0,The Holy Girl,Argentina,R,6.7

## (3.4) Basic visualizations

Some quick visualizations.

In [ ]:
dfc.corr(method='pearson')

In [ ]:
(dfc.content_rating
 .value_counts()
 .to_frame()  # Below are the default values, except `figsize`
 .plot.barh(subplots=False, sharex=None, sharey=False, layout=None, 
            figsize=(10, 5), use_index=True, title=None, grid=None, legend=True, 
            style=None, logx=False, logy=False, loglog=False, xticks=None, 
            yticks=None, xlim=None, ylim=None, rot=None, fontsize=None, 
            colormap=None, table=False, yerr=None, xerr=None, 
            secondary_y=False, sort_columns=False));

In [ ]:
df.gross.plot.kde(bw_method=0.1, grid=True, title='IMDB score', lw=3, figsize=(10, 5));

In [ ]:
plot = pd.plotting.scatter_matrix(df, alpha=0.5, figsize=(10, 5))

# (4) Selecting and computing new columns

This section is about selecting subsets of a datset, or creating new data from existing data, i.e.:

- Selecting a **single column**, or a **subset of columns**.
- Selecting a **subset of rows**, i.e. filtering.
- Chaining and/or combining the above operations to accomplish both.

## (4.1) Accessing index, columns and data

In [42]:
df.index

RangeIndex(start=0, stop=5043, step=1)

In [43]:
df.columns

Index(['director_name', 'gross', 'movie_title', 'country', 'content_rating',
       'imdb_score'],
      dtype='object')

In [44]:
# This is very useful when using data with libraries
df.to_numpy()

array([['James Cameron', 760505847.0, 'Avatar\xa0', 'USA', 'PG-13', 7.9],
       ['Gore Verbinski', 309404152.0,
        "Pirates of the Caribbean: At World's End\xa0", 'USA', 'PG-13',
        7.1],
       ['Sam Mendes', 200074175.0, 'Spectre\xa0', 'UK', 'PG-13', 6.8],
       ...,
       ['Benjamin Roberds', nan, 'A Plague So Pleasant\xa0', 'USA', nan,
        6.3],
       ['Daniel Hsia', 10443.0, 'Shanghai Calling\xa0', 'USA', 'PG-13',
        6.3],
       ['Jon Gunn', 85222.0, 'My Date with Drew\xa0', 'USA', 'PG', 6.6]],
      dtype=object)

In [ ]:
df.gross.dropna().to_numpy()

## (4.2) Selecting subsets of columns

In [ ]:
print(df.columns.tolist())  # Get the columns

In [45]:
df.director_name.head(3)  # Alternatively, use df['director_name'].head(3)

0     James Cameron
1    Gore Verbinski
2        Sam Mendes
Name: director_name, dtype: object

Selecting two or more columns.

In [ ]:
df[['movie_title', 'country']].head(2)

The most useful selection function is `df.loc[[row1, row2, ...], [col1, col2, ...]]`.

- `df.loc[:, [col1, col2]]` selects every row, and columns `[col1, col2]`
- `df.loc[[row1, row2], :]` selects rows `[row1, row2]`, and every column

In [48]:
df.loc[:, ['movie_title', 'country']].head(2)

                                 movie_title country
0                                    Avatar      USA
1  Pirates of the Caribbean: At World's End      USA

In [50]:
df.loc[10:13, ['movie_title', 'country']]

                                    movie_title country
10          Batman v Superman: Dawn of Justice      USA
11                            Superman Returns      USA
12                           Quantum of Solace       UK
13  Pirates of the Caribbean: Dead Man's Chest      USA

In [ ]:
a = df.loc[:, 'gross']  # Returns a Series
b = df.loc[:, ['gross']]  # Returns a DataFrame

print(type(a))
print(type(b))

In [52]:
df.head()

,director_name,gross,movie_title,country,content_rating,imdb_score
0,James Cameron,760505847.0,Avatar,USA,PG-13,7.9
1,Gore Verbinski,309404152.0,Pirates of the Caribbean: At World's End,USA,PG-13,7.1
2,Sam Mendes,200074175.0,Spectre,UK,PG-13,6.8
3,Christopher Nolan,448130642.0,The Dark Knight Rises,USA,PG-13,8.5
4,Doug Walker,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,7.1

Instead of selecting a subset of columns to *keep*, we can select a subset to *drop*.

In [53]:
# Drop specified labels from rows or columns
df.drop(columns=['director_name', 'gross', 'movie_title']).head(3)

  country content_rating  imdb_score
0     USA          PG-13         7.9
1     USA          PG-13         7.1
2      UK          PG-13         6.8

In [54]:
df.head()

,director_name,gross,movie_title,country,content_rating,imdb_score
0,James Cameron,760505847.0,Avatar,USA,PG-13,7.9
1,Gore Verbinski,309404152.0,Pirates of the Caribbean: At World's End,USA,PG-13,7.1
2,Sam Mendes,200074175.0,Spectre,UK,PG-13,6.8
3,Christopher Nolan,448130642.0,The Dark Knight Rises,USA,PG-13,8.5
4,Doug Walker,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,7.1

In [55]:
# Integer-location based indexing
df.iloc[1:3, [0, 1, 2]]

    director_name        gross                                movie_title
1  Gore Verbinski  309404152.0  Pirates of the Caribbean: At World's End
2      Sam Mendes  200074175.0                                   Spectre

## (4.3) Selecting subsets of rows

In [ ]:
# Return the first `n` rows
df.head(n=1)

In [51]:
# Access a group of rows and columns by label(s) or a boolean array
df.loc[[0], :]

   director_name        gross movie_title country content_rating  imdb_score
0  James Cameron  760505847.0     Avatar      USA          PG-13         7.9

In [ ]:
df.loc[[0]]

In [ ]:
# Top three movies / TV-series not from the USA
df[df.country != 'USA'].nlargest(3, 'imdb_score')

In [ ]:
# Best non-American films, with content rating PG-13
mask = (df.country != 'USA') & (df.content_rating == 'PG-13')
df[mask].nlargest(3, 'imdb_score')

## (4.4) Selecting subsets of rows *and* columns

In [ ]:
# Above average movies, with the title containing 'ring'
row_mask = ((df.imdb_score > df.imdb_score.mean()) & 
             df.movie_title.str.contains('ring'))
df.loc[row_mask, ['director_name', 'movie_title', 'country']]

In [ ]:
# Columns containing and underscore
cols = [c for c in df.columns if '_' in c]
df.loc[:, cols].head()

In [ ]:
# Numerical columns
numeric_cols = df.dtypes[df.dtypes == np.float].index.tolist()
df.loc[:, numeric_cols].head(n=2)

## (4.5) Creating new columns

In [ ]:
temp = df.copy()  # Copy the DataFrame

# Create a new column - based on the gross income
temp['log_gross'] = temp['gross'].apply(np.log10)

temp.head(2)

In [ ]:
temp.plot.scatter(x='imdb_score', y='log_gross', alpha=0.2, s=15, figsize=(10, 5));

In [ ]:
# Assign new columns to a DataFrame, returning a new object
# (a copy) with the new columns added to the original ones.
(temp.assign(log_gross=lambda df:df.gross.apply(np.log10))).head()

# One advantage is that method chaining can be used
(temp
     .assign(log_gross=lambda df:df.gross.apply(np.log10)) # Create a new column
     .loc[:, ['country', 'content_rating', 'log_gross']] # Filter
     .groupby(['country', 'content_rating']) # Group by and mean
     .mean()
     .reset_index() # Reset the index to sort
     .sort_values(['country', 'log_gross'], ascending=[True, False]) # Sort the results
     .set_index(['country', 'content_rating']) # Re-index
     .assign(log_gross=lambda df:df.log_gross.round(2)) # Re-define the column and round it
     .head(5)
)

## (4.6) Applying functions

On a `pd.Series`:

- `pd.Series.map` applies an elementwise $f: \mathbb{R} \to \mathbb{R}$ function (e.g. `str`, or `float`)
- `pd.Series.apply` applies a vectorized $f: \mathbb{R}^n \to \mathbb{R}^n$ function  (e.g. `log`, or `sin`)
- `pd.Series.aggregate` applies an aggreation $f: \mathbb{R}^n \to \mathbb{R}$ function  (e.g. `mean`, or `std`)

On a `pd.DataFrame`:

- `pd.DataFrame.applymap` applies an elementwise $f: \mathbb{R} \to \mathbb{R}$ function to every element
- `pd.DataFrame.apply` applies a vectorized $f: \mathbb{R}^n \to \mathbb{R}^n$ function to every element
- `pd.DataFrame.aggregate` applies an aggreation $f: \mathbb{R}^n \to \mathbb{R}$ function over an axis

### Functions on Series

In [ ]:
# Map values of Series using input correspondence (a dict, Series, or function).
df.gross.map(float).head(2)

In [61]:
# Dictionaries are also maps, but brittle since no keys maps to NaN
(df.content_rating
    .map({'PG-13':'inappropriate for children under 13', 
          'PG': 'may not be suitable for children'}, na_action='ignore')
    .value_counts(dropna=False)
    .to_frame())

                                     count
content_rating
NaN                                   2881
inappropriate for children under 13   1461
may not be suitable for children       701

The `df.apply` method applies a NumPy [ufunc](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html).

> A *universal function* (or ufunc for short) is a function that operates on ndarrays in an **element-by-element** fashion.

In [57]:
# Invoke function on values of Series. Can be ufunc (a NumPy function
# that applies to the entire Series) or a Python function that only works
# on single values
df.gross.apply(np.log10).head(2)

0    8.881103
1    8.490526
Name: gross, dtype: float64

In [58]:
df.gross.head(2).apply(np.log10)

0    8.881103
1    8.490526
Name: gross, dtype: float64

In [56]:
# Aggregate using one or more operations over the specified axis.
df.gross.aggregate(np.mean, axis=0)

C:\Users\5\AppData\Local\Temp\ipykernel_24276\2400253960.py:2: FutureWarning: The provided callable <function mean at 0x000002259D9BFD80> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.gross.aggregate(np.mean, axis=0)

np.float64(48468407.52680933)

---------------

### Functions on DataFrames

In [ ]:
df.loc[:, ['gross', 'imdb_score']].apply(np.log).head(2)

In [ ]:
df.loc[:, ['gross', 'imdb_score']].applymap(int).head(2)

In [ ]:
df.loc[:, ['gross', 'imdb_score']].mean().head(2)

In [64]:

df.loc[:, ['gross', 'imdb_score']].head()

         gross  imdb_score
0  760505847.0         7.9
1  309404152.0         7.1
2  200074175.0         6.8
3  448130642.0         8.5
4          NaN         7.1

In [63]:
# Or specify your own aggregation function
def spread(array):
    return np.max(array) - np.min(array)

df.loc[:, ['gross', 'imdb_score']].aggregate(spread, axis=0)

gross         760505685.0
imdb_score            7.9
dtype: float64

In [66]:
print(df['imdb_score'].min())
print(df['imdb_score'].max())

1.6
9.5

In [69]:
df['imdb_score'].agg(['sum', 'max', 'min'], axis=0)

sum    32487.7
max        9.5
min        1.6
Name: imdb_score, dtype: float64

## Next up ...

**In the next video:** filtering and sorting, split-apply-combine, plotting, time series, machine learning, ...