# Introduction to pandas

#### 1. What is data science ?

Data science is the process of analysing data and extracting the useful informations.To extract the useful infomations first you need to analyse the dataset by performing some operations. <br>
In another way you can say that it is the science of data,fiding hidden relationships and using these to predict the future. <br>
![alt text](datasets/ds1.jpg) <br>
Data science combining various fields like data preprocessing  ,domain expertise, Machine Learning, Mathematics, Statistics.Here we only talk about data preprocessing in efficient way by pandas.

#### 2. What is pandas ?

Pandas is used as data cleaning tool in the field of data science.You can do whatever operation you want in the dataset with this tool.Now question arises, can we clean or change the value in the dataset manually ? Answer is yes we can if size of the dataset is small.What if we have a large dataset then we can not do it manually it will take a lot of time.Pandas makes data science very easy and effective.

###### To use pandas you need to first import the pandas module in your program

In [3]:
import pandas as pd #Now you can use pandas functions by pd.read_csv("path") etc..

### Reading CSV and Excel sheets:

##### d=pd.read_csv("path"):
 * pd.read_csv() is the function to read the CSV(Comma separated values) file from your computer.
 * In the function you have to pass "path" of the CSV file under quote.
 * Store the dataframe in any variable,here i stored it in variable "d".
 * read_csv() function makes the CSV file into dataframe so that you can access it just like a disctionary.

##### d=pd.read_excel("path") : 
 * It is same as the read_csv() but it reads  excel sheet or file.
Here i am using the weather dataset which has all the data of weather.
######  In my case,weather.csv file is in my current directory that is why the path of the file is file name itself.

In [18]:
d=pd.read_csv('datasets/weather.csv') 
# returning dataframe object
d.head()
#printing dataframe d

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

#### How many rows ?

In [5]:
print(len(d))
# there are 96453 rows

96453

### Getting first n-rows of dataset
  * To see the first five rows call head() function with dataframe object. <br>
      for example-  
      <code> d.head() </code> <br>
  * If you want to view first n-rows <br>
      <code> d.head(n) </code>

In [6]:
d.head() # first five rows

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [19]:
d.head(3) # to print first n=3 rows

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.

### Getting last n-rows of dataset
  * Call the tail() function <br>
     <code> d.tail() </code> <br>
It will show only last five rows of dataframe d. <br>
  * If you want to see last n-rows - <br>
     <code> d.tail(n) </code>

In [8]:
d.tail() #last five rows

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [20]:
d.tail(2) # last 2 rows

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

### Slicing in the dataframe
 * Suppose you want to get 3 rows of the dataframe ranging from row 21 to 23. <br>
   <code> d[21<b>:</b>23+1] </code>

In [25]:
print(len(d[21:24]))

3

In [24]:
d[21:24]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
21,2006-04-01 21:00:00.000 +0200,Mostly Cloudy,rain,11.183333,11.183333,0.76,4.9266,160.0,9.9820,0.0,1015.77,Partly cloudy throughout the day.
22,2006-04-01 22:00:00.000 +0200,Partly Cloudy,rain,10.116667,10.116667,0.79,6.6493,163.0,15.8263,0.0,1015.40,Partly cloudy throughout the day.
23,2006-04-01 23:00:00.000 +0200,Mostly Cloudy,rain,10.200000,10.200000,0.77,3.9284,152.0,14.9569,0.0,1015.51,Partly cloudy throughout the day.

### Accesing the particular column of dataframe :
 * You can access the particular column of the dataframe just my mentioning its name under quote with dataframe d.<br>
    for example you want to access Humidity column e.i, <br>
    
    <code> d['Humidity'] </code>

In [11]:
d['Humidity'].head(10) 
#Here i have applied head() function just to see only first 10 values because humidity 
#column has too many values

0    0.89
1    0.86
2    0.89
3    0.83
4    0.83
5    0.85
6    0.95
7    0.89
8    0.82
9    0.72
Name: Humidity, dtype: float64

### Finding min, max and average of a column:
  * <b>min() :</b> To find minimum of a column
  * <b>max() :</b> To find maximum of a column <br>
  * <b>mean() :</b> To find average of a column <br>
  
Find minimum and maximum of Humidity column-

In [12]:
d['Humidity'].min() 
#Printing minimum value of Humidity

0.0

In [13]:
d['Humidity'].max()
#Print maximum value Humidity

1.0

In [14]:
d['Humidity'].mean()
#Print average value Humidty

np.float64(0.7348989663359355)

### Conditional statements
  * <code>d["your column"]["your condition"] </code> <br>
   It will return all the values in which your condition holds true.
#### Examples : <br>
  * Find temp when Humidity is minimum<br>
  
    <code> d['Temperature(C)'][d['Humidity']==d['Humidity'].min() ]</code> <br><br>
    
  * Find temp when Humidity is maximum <br>
  
    <code> d['Temperature(C)'][d['Humidity']==d['Humidity'].max() ] </code>

In [26]:
d['Temperature (C)'][d['Humidity']==d['Humidity'].min()]

19958    -1.111111
28101   -15.000000
28103   -15.555556
28110   -13.888889
29627     1.111111
54840   -15.555556
54858   -15.000000
54870   -16.111111
54872   -15.000000
54873   -13.888889
55086   -12.777778
55088   -12.777778
55349   -12.222222
55350   -12.222222
55352   -12.222222
55412   -17.777778
55469   -17.777778
55472   -17.777778
55473   -16.111111
55481   -12.777778
55508   -16.111111
55511   -17.777778
Name: Temperature (C), dtype: float64

In [16]:
 d['Temperature (C)'][d['Humidity']==d['Humidity'].max()]

319      11.972222
342       7.155556
390       7.688889
535       5.933333
536      10.405556
           ...
95907    14.905556
96123     7.594444
96148     8.838889
96363    12.338889
96364    12.872222
Name: Temperature (C), Length: 2890, dtype: float64

###### In the same way you can apply various condition and analyse it hidden features

### Replacing NaN with specific value
 * Here i am replacing all NaN value with 0.

In [17]:
d.fillna(0,inplace=True)