## DataFrame Object

DataFrame is the a main object in pandas.It is used to represent data with rows and columns(tabular or excel spreadshee like data

In [1]:
#Imprting pandas module
import pandas as pd

In [2]:
#Now read a csv file
d=pd.read_csv('datasets/weather.csv')
#print dataframe "d"
d.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.

### Creating DataFrame with dictionary
  * You can also create DataFrame with python dictionary very easily.
  * You just need to call DataFrame() function and pass the dictionary as a argument in the function.
  * <b>Note:</b> Notice one thing that i have taken all the columns of same length because you can not make dataframe object if your dictionary has variable column length

In [3]:
#Creatiing my own dictionary
mydict={
         'dates':['02-01-12','03-01-12','04-01-12','05-01-12','06-01-12'],
         'day':['sunny','rainy','hot','sunny','hot'],
         'wind-speed':[12,34,45,56,67],
         'temp':[45,46,47,48,49]
       }
#Converting disction to dataframe object
df=pd.DataFrame(mydict)

#Printing the dataframe
df

      dates    day  wind-speed  temp
0  02-01-12  sunny          12    45
1  03-01-12  rainy          34    46
2  04-01-12    hot          45    47
3  05-01-12  sunny          56    48
4  06-01-12    hot          67    49

### Shape of the dataframe
  * <b>df.shape :</b> It will return a tuple (rows,columns)

In [4]:
df.shape

(5, 4)

### Accessing columns :
 * What if you want to print only two columns

In [5]:
df[['day','temp']]

     day  temp
0  sunny    45
1  rainy    46
2    hot    47
3  sunny    48
4    hot    49

### Statistics of your dataframe
 * You can see the statistics of your dataframe by calling describe() function
 * It will print count of the columns,mean,SD,min,max etc..

In [6]:
d.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96154.000000,96154.000000,96154.000000,96154.000000,96154.000000,96154.000000,96154.0,96154.000000
mean,11.916386,10.835865,0.735167,10.822505,187.538303,10.335954,0.0,1003.180646
std,9.554458,10.701512,0.195315,6.916388,107.325312,4.190119,0.0,117.147172
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.605556,2.283333,0.600000,5.844300,116.000000,8.339800,0.0,1011.880000
50%,11.977778,11.977778,0.780000,9.982000,180.000000,10.046400,0.0,1016.430000
75%,18.827778,18.827778,0.890000,14.135800,290.000000,14.812000,0.0,1021.070000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

### Condition:
 * To get dataframe where temperature is greater than 9

In [16]:
d1=d[d['Temperature (C)']>9]
d1.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258,14.9569,0,1016.66,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259,9.9820,0,1017.37,Partly cloudy throughout the day.

In [ ]:
#How many rows and columns are there in 'd1'?
# d1.shape
len(d1)

56345

### Changing Index
 * Pandas has its own indexing by default from 0 to row no 
 * We can also reset its index by set_index() function

In [9]:
df

      dates    day  wind-speed  temp
0  02-01-12  sunny          12    45
1  03-01-12  rainy          34    46
2  04-01-12    hot          45    47
3  05-01-12  sunny          56    48
4  06-01-12    hot          67    49

In [10]:
df.set_index('dates',inplace=True)

In [11]:
df

            day  wind-speed  temp
dates
02-01-12  sunny          12    45
03-01-12  rainy          34    46
04-01-12    hot          45    47
05-01-12  sunny          56    48
06-01-12    hot          67    49

#### Now we can find the specific value rows

In [12]:
df.loc['02-01-12']

day           sunny
wind-speed       12
temp             45
Name: 02-01-12, dtype: object

In [13]:
df.iloc[4]

day           hot
wind-speed     67
temp           49
Name: 06-01-12, dtype: object

In [14]:
df.iloc[0:3]

            day  wind-speed  temp
dates
02-01-12  sunny          12    45
03-01-12  rainy          34    46
04-01-12    hot          45    47

In [15]:
df.reset_index()

      dates    day  wind-speed  temp
0  02-01-12  sunny          12    45
1  03-01-12  rainy          34    46
2  04-01-12    hot          45    47
3  05-01-12  sunny          56    48
4  06-01-12    hot          67    49